/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class JNIProvider */

#ifndef _Included_JNIProvider
#define _Included_JNIProvider
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     JNIProvider
 * Method:    generateToken
 * Signature: ([Ljava/lang/String;[Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_JNIProvider_generateToken
  (JNIEnv *, jobject, jobjectArray, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
